//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BatteryControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BatteryControlProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BatterySystem" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatterySystem"/&gt;
 *         &lt;element name="BatterySystemControl" type="{http://openfmb.org/xsd/2015/12/openfmb/batterymodule}BatterySystemControl"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BatteryControlProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule", propOrder = {
    "batterySystem",
    "batterySystemControl"
})
@XmlRootElement(name = "BatteryControlProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/batterymodule")
public class BatteryControlProfile
    extends Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "BatterySystem", required = true)
    protected BatterySystem batterySystem;
    @XmlElement(name = "BatterySystemControl", required = true)
    protected BatterySystemControl batterySystemControl;

    /**
     * Gets the value of the batterySystem property.
     * 
     * @return
     *     possible object is
     *     {@link BatterySystem }
     *     
     */
    public BatterySystem getBatterySystem() {
        return batterySystem;
    }

    /**
     * Sets the value of the batterySystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatterySystem }
     *     
     */
    public void setBatterySystem(BatterySystem value) {
        this.batterySystem = value;
    }

    /**
     * Gets the value of the batterySystemControl property.
     * 
     * @return
     *     possible object is
     *     {@link BatterySystemControl }
     *     
     */
    public BatterySystemControl getBatterySystemControl() {
        return batterySystemControl;
    }

    /**
     * Sets the value of the batterySystemControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BatterySystemControl }
     *     
     */
    public void setBatterySystemControl(BatterySystemControl value) {
        this.batterySystemControl = value;
    }

}
