//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Container complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Container"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="logicalDeviceID" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="timestamp" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Container", propOrder = {
    "logicalDeviceID",
    "timestamp"
})
@XmlSeeAlso({
    WeatherDataProfile.class,
    SolarForecastProfile.class,
    SolarCapabilityProfile.class,
    SolarEventProfile.class,
    SolarReadingProfile.class,
    SolarControlProfile.class,
    ShuntReadingProfile.class,
    ShuntControlProfile.class,
    ShuntStatusProfile.class,
    SecurityEventProfile.class,
    ResourceStatusProfile.class,
    ResourceReadingProfile.class,
    RegulatorReadingProfile.class,
    RegulatorStatusProfile.class,
    RecloserControlProfile.class,
    RecloserEventProfile.class,
    RecloserReadingProfile.class,
    LoadForecastProfile.class,
    LoadStatusProfile.class,
    LoadControlProfile.class,
    LoadReadingProfile.class,
    InterchangeScheduleProfile.class,
    GenerationControlProfile.class,
    GenerationEventProfile.class,
    GenerationReadingProfile.class,
    GenerationForecastProfile.class,
    BatteryEventProfile.class,
    BatteryReadingProfile.class,
    BatteryControlProfile.class
})
public class Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(required = true)
    protected String logicalDeviceID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar timestamp;

    /**
     * Gets the value of the logicalDeviceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogicalDeviceID() {
        return logicalDeviceID;
    }

    /**
     * Sets the value of the logicalDeviceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogicalDeviceID(String value) {
        this.logicalDeviceID = value;
    }

    /**
     * Gets the value of the timestamp property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTimestamp(XMLGregorianCalendar value) {
        this.timestamp = value;
    }

}
