//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CurveStyleKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CurveStyleKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="constantYValue"/&gt;
 *     &lt;enumeration value="straightLineYValues"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CurveStyleKind")
@XmlEnum
public enum CurveStyleKind {


    /**
     * The Y-axis values are assumed constant until the next curve point and prior to the first curve point.
     * 
     */
    @XmlEnumValue("constantYValue")
    CONSTANT_Y_VALUE("constantYValue"),

    /**
     * The Y-axis values are assumed to be a straight line between values.  Also known as linear interpolation.
     * 
     */
    @XmlEnumValue("straightLineYValues")
    STRAIGHT_LINE_Y_VALUES("straightLineYValues");
    private final String value;

    CurveStyleKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CurveStyleKind fromValue(String v) {
        for (CurveStyleKind c: CurveStyleKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
