//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Multi-purpose data points for defining a curve.  The use of this generic class is discouraged if a more specific class  can be used to specify the x and y axis values along with their specific data types.
 * 
 * <p>Java class for CurveData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CurveData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="xvalue" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="y1value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="y2value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="y3value" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CurveData", propOrder = {
    "xvalue",
    "y1Value",
    "y2Value",
    "y3Value"
})
@XmlRootElement(name = "CurveData")
public class CurveData
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected Float xvalue;
    @XmlElement(name = "y1value")
    protected Float y1Value;
    @XmlElement(name = "y2value")
    protected Float y2Value;
    @XmlElement(name = "y3value")
    protected Float y3Value;

    /**
     * Gets the value of the xvalue property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getXvalue() {
        return xvalue;
    }

    /**
     * Sets the value of the xvalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setXvalue(Float value) {
        this.xvalue = value;
    }

    /**
     * Gets the value of the y1Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY1Value() {
        return y1Value;
    }

    /**
     * Sets the value of the y1Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY1Value(Float value) {
        this.y1Value = value;
    }

    /**
     * Gets the value of the y2Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY2Value() {
        return y2Value;
    }

    /**
     * Sets the value of the y2Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY2Value(Float value) {
        this.y2Value = value;
    }

    /**
     * Gets the value of the y3Value property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getY3Value() {
        return y3Value;
    }

    /**
     * Sets the value of the y3Value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setY3Value(Float value) {
        this.y3Value = value;
    }

}
