//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Instructs an end device (or an end device group) to perform a specified action.
 * 
 * <p>Java class for EndDeviceControl complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EndDeviceControl"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="issueID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="scheduledInterval" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}DateTimeInterval" minOccurs="0"/&gt;
 *         &lt;element name="EndDeviceControlType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}EndDeviceControlType" minOccurs="0"/&gt;
 *         &lt;element name="SetPoints" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}SetPoint" maxOccurs="100" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EndDeviceControl", propOrder = {
    "issueID",
    "name",
    "scheduledInterval",
    "endDeviceControlType",
    "setPoints"
})
@XmlSeeAlso({
    SolarControl.class,
    ShuntControl.class,
    RecloserControl.class,
    LoadControl.class,
    GenerationControl.class,
    BatterySystemControl.class
})
public class EndDeviceControl
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String issueID;
    protected String name;
    protected DateTimeInterval scheduledInterval;
    @XmlElement(name = "EndDeviceControlType")
    protected EndDeviceControlType endDeviceControlType;
    @XmlElement(name = "SetPoints")
    protected List<SetPoint> setPoints;

    /**
     * Gets the value of the issueID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueID() {
        return issueID;
    }

    /**
     * Sets the value of the issueID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueID(String value) {
        this.issueID = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the scheduledInterval property.
     * 
     * @return
     *     possible object is
     *     {@link DateTimeInterval }
     *     
     */
    public DateTimeInterval getScheduledInterval() {
        return scheduledInterval;
    }

    /**
     * Sets the value of the scheduledInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTimeInterval }
     *     
     */
    public void setScheduledInterval(DateTimeInterval value) {
        this.scheduledInterval = value;
    }

    /**
     * Gets the value of the endDeviceControlType property.
     * 
     * @return
     *     possible object is
     *     {@link EndDeviceControlType }
     *     
     */
    public EndDeviceControlType getEndDeviceControlType() {
        return endDeviceControlType;
    }

    /**
     * Sets the value of the endDeviceControlType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndDeviceControlType }
     *     
     */
    public void setEndDeviceControlType(EndDeviceControlType value) {
        this.endDeviceControlType = value;
    }

    /**
     * Gets the value of the setPoints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setPoints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetPoints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetPoint }
     * 
     * 
     */
    public List<SetPoint> getSetPoints() {
        if (setPoints == null) {
            setPoints = new ArrayList<SetPoint>();
        }
        return this.setPoints;
    }

}
