//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnergyProductKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnergyProductKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="FIRM"/&gt;
 *     &lt;enumeration value="NFRM"/&gt;
 *     &lt;enumeration value="DYN"/&gt;
 *     &lt;enumeration value="WHL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnergyProductKind")
@XmlEnum
public enum EnergyProductKind {


    /**
     * Firm
     * 
     */
    FIRM,

    /**
     * Non Firm
     * 
     */
    NFRM,

    /**
     * Dynamic
     * 
     */
    DYN,

    /**
     * Wheeling
     * 
     */
    WHL;

    public String value() {
        return name();
    }

    public static EnergyProductKind fromValue(String v) {
        return valueOf(v);
    }

}
