//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Generic user of energy - a  point of consumption on the power system model.
 * 
 * <p>Java class for EnergyConsumer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EnergyConsumer"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}IdentifiedObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operatingLimit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EnergyConsumer", namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", propOrder = {
    "operatingLimit"
})
@XmlRootElement(name = "EnergyConsumer", namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule")
public class EnergyConsumer
    extends IdentifiedObject
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected String operatingLimit;

    /**
     * Gets the value of the operatingLimit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatingLimit() {
        return operatingLimit;
    }

    /**
     * Sets the value of the operatingLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatingLimit(String value) {
        this.operatingLimit = value;
    }

}
