//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Interchange schedule class to hold information for interchange schedules such as import export type, energy type, and etc.
 * 
 * <p>Java class for InterchangeSchedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InterchangeSchedule"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Curve"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="directionType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}InterTieDirectionKind" minOccurs="0"/&gt;
 *         &lt;element name="energyType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}MarketProductKind" minOccurs="0"/&gt;
 *         &lt;element name="intervalLength" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/&gt;
 *         &lt;element name="scheduleType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}EnergyProductKind" minOccurs="0"/&gt;
 *         &lt;element name="OptimizedMicroGridMarket" type="{http://openfmb.org/xsd/2015/12/openfmb/interchangemodule}OptimizedMicroGridMarket" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InterchangeSchedule", namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule", propOrder = {
    "directionType",
    "energyType",
    "intervalLength",
    "scheduleType",
    "optimizedMicroGridMarket"
})
@XmlRootElement(name = "InterchangeSchedule", namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule")
public class InterchangeSchedule
    extends Curve
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlSchemaType(name = "string")
    protected InterTieDirectionKind directionType;
    @XmlSchemaType(name = "string")
    protected MarketProductKind energyType;
    protected Integer intervalLength;
    @XmlSchemaType(name = "string")
    protected EnergyProductKind scheduleType;
    @XmlElement(name = "OptimizedMicroGridMarket")
    protected OptimizedMicroGridMarket optimizedMicroGridMarket;

    /**
     * Gets the value of the directionType property.
     * 
     * @return
     *     possible object is
     *     {@link InterTieDirectionKind }
     *     
     */
    public InterTieDirectionKind getDirectionType() {
        return directionType;
    }

    /**
     * Sets the value of the directionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterTieDirectionKind }
     *     
     */
    public void setDirectionType(InterTieDirectionKind value) {
        this.directionType = value;
    }

    /**
     * Gets the value of the energyType property.
     * 
     * @return
     *     possible object is
     *     {@link MarketProductKind }
     *     
     */
    public MarketProductKind getEnergyType() {
        return energyType;
    }

    /**
     * Sets the value of the energyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketProductKind }
     *     
     */
    public void setEnergyType(MarketProductKind value) {
        this.energyType = value;
    }

    /**
     * Gets the value of the intervalLength property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getIntervalLength() {
        return intervalLength;
    }

    /**
     * Sets the value of the intervalLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setIntervalLength(Integer value) {
        this.intervalLength = value;
    }

    /**
     * Gets the value of the scheduleType property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyProductKind }
     *     
     */
    public EnergyProductKind getScheduleType() {
        return scheduleType;
    }

    /**
     * Sets the value of the scheduleType property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyProductKind }
     *     
     */
    public void setScheduleType(EnergyProductKind value) {
        this.scheduleType = value;
    }

    /**
     * Gets the value of the optimizedMicroGridMarket property.
     * 
     * @return
     *     possible object is
     *     {@link OptimizedMicroGridMarket }
     *     
     */
    public OptimizedMicroGridMarket getOptimizedMicroGridMarket() {
        return optimizedMicroGridMarket;
    }

    /**
     * Sets the value of the optimizedMicroGridMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link OptimizedMicroGridMarket }
     *     
     */
    public void setOptimizedMicroGridMarket(OptimizedMicroGridMarket value) {
        this.optimizedMicroGridMarket = value;
    }

}
