//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoadControlProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadControlProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="EnergyConsumer" type="{http://openfmb.org/xsd/2015/12/openfmb/loadmodule}EnergyConsumer"/&gt;
 *         &lt;element name="LoadControl" type="{http://openfmb.org/xsd/2015/12/openfmb/loadmodule}LoadControl"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadControlProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule", propOrder = {
    "energyConsumer",
    "loadControl"
})
@XmlRootElement(name = "LoadControlProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/loadmodule")
public class LoadControlProfile
    extends Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "EnergyConsumer", required = true)
    protected EnergyConsumer energyConsumer;
    @XmlElement(name = "LoadControl", required = true)
    protected LoadControl loadControl;

    /**
     * Gets the value of the energyConsumer property.
     * 
     * @return
     *     possible object is
     *     {@link EnergyConsumer }
     *     
     */
    public EnergyConsumer getEnergyConsumer() {
        return energyConsumer;
    }

    /**
     * Sets the value of the energyConsumer property.
     * 
     * @param value
     *     allowed object is
     *     {@link EnergyConsumer }
     *     
     */
    public void setEnergyConsumer(EnergyConsumer value) {
        this.energyConsumer = value;
    }

    /**
     * Gets the value of the loadControl property.
     * 
     * @return
     *     possible object is
     *     {@link LoadControl }
     *     
     */
    public LoadControl getLoadControl() {
        return loadControl;
    }

    /**
     * Sets the value of the loadControl property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadControl }
     *     
     */
    public void setLoadControl(LoadControl value) {
        this.loadControl = value;
    }

}
