//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MarketKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="DAM"/&gt;
 *     &lt;enumeration value="RTM"/&gt;
 *     &lt;enumeration value="HAM"/&gt;
 *     &lt;enumeration value="RUC"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MarketKind")
@XmlEnum
public enum MarketKind {


    /**
     * Day ahead market.
     * 
     */
    DAM,

    /**
     * Real time market.
     * 
     */
    RTM,

    /**
     * Hour Ahead Market.
     * 
     */
    HAM,

    /**
     * Residual Unit Commitment.
     * 
     */
    RUC;

    public String value() {
        return name();
    }

    public static MarketKind fromValue(String v) {
        return valueOf(v);
    }

}
