//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MarketProductKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MarketProductKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EN"/&gt;
 *     &lt;enumeration value="RU"/&gt;
 *     &lt;enumeration value="RD"/&gt;
 *     &lt;enumeration value="SR"/&gt;
 *     &lt;enumeration value="NR"/&gt;
 *     &lt;enumeration value="RC"/&gt;
 *     &lt;enumeration value="LFU"/&gt;
 *     &lt;enumeration value="REG"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MarketProductKind")
@XmlEnum
public enum MarketProductKind {


    /**
     * energy type
     * 
     */
    EN,

    /**
     * regulation up
     * 
     */
    RU,

    /**
     * regulation down
     * 
     */
    RD,

    /**
     * spinning reserve
     * 
     */
    SR,

    /**
     * non spinning reserve
     * 
     */
    NR,

    /**
     * Residual Unit Commitment
     * 
     */
    RC,

    /**
     * Load following up
     * 
     */
    LFU,

    /**
     * Regulation
     * 
     */
    REG;

    public String value() {
        return name();
    }

    public static MarketProductKind fromValue(String v) {
        return valueOf(v);
    }

}
