//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class represent an actual instance of a planned market. For example, a Day Ahead market opens with the Bid Submission, ends with the closing of the Bid Submission. The market run represent the whole process. MarketRuns can be defined for markets such as Day Ahead Market, Real Time Market, Hour Ahead Market, Week Ahead Market,...
 * 
 * <p>Java class for MarketRun complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketRun"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="executionType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}ExecutionKind" minOccurs="0"/&gt;
 *         &lt;element name="marketEndTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="marketID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="marketRunID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="marketStartTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="marketType" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}MarketKind" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketRun", namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule", propOrder = {
    "executionType",
    "marketEndTime",
    "marketID",
    "marketRunID",
    "marketStartTime",
    "marketType"
})
@XmlRootElement(name = "MarketRun", namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule")
public class MarketRun
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlSchemaType(name = "string")
    protected ExecutionKind executionType;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar marketEndTime;
    protected String marketID;
    protected String marketRunID;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar marketStartTime;
    @XmlSchemaType(name = "string")
    protected MarketKind marketType;

    /**
     * Gets the value of the executionType property.
     * 
     * @return
     *     possible object is
     *     {@link ExecutionKind }
     *     
     */
    public ExecutionKind getExecutionType() {
        return executionType;
    }

    /**
     * Sets the value of the executionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExecutionKind }
     *     
     */
    public void setExecutionType(ExecutionKind value) {
        this.executionType = value;
    }

    /**
     * Gets the value of the marketEndTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarketEndTime() {
        return marketEndTime;
    }

    /**
     * Sets the value of the marketEndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarketEndTime(XMLGregorianCalendar value) {
        this.marketEndTime = value;
    }

    /**
     * Gets the value of the marketID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketID() {
        return marketID;
    }

    /**
     * Sets the value of the marketID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketID(String value) {
        this.marketID = value;
    }

    /**
     * Gets the value of the marketRunID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketRunID() {
        return marketRunID;
    }

    /**
     * Sets the value of the marketRunID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketRunID(String value) {
        this.marketRunID = value;
    }

    /**
     * Gets the value of the marketStartTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMarketStartTime() {
        return marketStartTime;
    }

    /**
     * Sets the value of the marketStartTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMarketStartTime(XMLGregorianCalendar value) {
        this.marketStartTime = value;
    }

    /**
     * Gets the value of the marketType property.
     * 
     * @return
     *     possible object is
     *     {@link MarketKind }
     *     
     */
    public MarketKind getMarketType() {
        return marketType;
    }

    /**
     * Sets the value of the marketType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketKind }
     *     
     */
    public void setMarketType(MarketKind value) {
        this.marketType = value;
    }

}
