//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Market (e.g. Day Ahead Market, RealTime Market) with a description of the the Market operation control parameters.
 * 
 * <p>Java class for Market complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Market"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}IdentifiedObject"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="actualEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="actualStart" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="dst" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="end" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="localTimeZone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="start" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="timeIntervalLength" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/&gt;
 *         &lt;element name="tradingDay" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="tradingPeriod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MarketFactors" type="{http://openfmb.org/xsd/2015/12/openfmb/interchangemodule}MarketFactors" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="MarketRun" type="{http://openfmb.org/xsd/2015/12/openfmb/interchangemodule}MarketRun" maxOccurs="100" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Market", namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule", propOrder = {
    "actualEnd",
    "actualStart",
    "dst",
    "end",
    "localTimeZone",
    "start",
    "status",
    "timeIntervalLength",
    "tradingDay",
    "tradingPeriod",
    "marketFactors",
    "marketRuns"
})
@XmlSeeAlso({
    OptimizedMicroGridMarket.class
})
public class Market
    extends IdentifiedObject
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualEnd;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar actualStart;
    protected Boolean dst;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar end;
    protected String localTimeZone;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar start;
    protected String status;
    protected Float timeIntervalLength;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar tradingDay;
    protected String tradingPeriod;
    @XmlElement(name = "MarketFactors")
    protected List<MarketFactors> marketFactors;
    @XmlElement(name = "MarketRun")
    protected List<MarketRun> marketRuns;

    /**
     * Gets the value of the actualEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualEnd() {
        return actualEnd;
    }

    /**
     * Sets the value of the actualEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualEnd(XMLGregorianCalendar value) {
        this.actualEnd = value;
    }

    /**
     * Gets the value of the actualStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getActualStart() {
        return actualStart;
    }

    /**
     * Sets the value of the actualStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setActualStart(XMLGregorianCalendar value) {
        this.actualStart = value;
    }

    /**
     * Gets the value of the dst property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDst() {
        return dst;
    }

    /**
     * Sets the value of the dst property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDst(Boolean value) {
        this.dst = value;
    }

    /**
     * Gets the value of the end property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEnd() {
        return end;
    }

    /**
     * Sets the value of the end property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEnd(XMLGregorianCalendar value) {
        this.end = value;
    }

    /**
     * Gets the value of the localTimeZone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalTimeZone() {
        return localTimeZone;
    }

    /**
     * Sets the value of the localTimeZone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalTimeZone(String value) {
        this.localTimeZone = value;
    }

    /**
     * Gets the value of the start property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStart() {
        return start;
    }

    /**
     * Sets the value of the start property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStart(XMLGregorianCalendar value) {
        this.start = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the timeIntervalLength property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getTimeIntervalLength() {
        return timeIntervalLength;
    }

    /**
     * Sets the value of the timeIntervalLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setTimeIntervalLength(Float value) {
        this.timeIntervalLength = value;
    }

    /**
     * Gets the value of the tradingDay property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getTradingDay() {
        return tradingDay;
    }

    /**
     * Sets the value of the tradingDay property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setTradingDay(XMLGregorianCalendar value) {
        this.tradingDay = value;
    }

    /**
     * Gets the value of the tradingPeriod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradingPeriod() {
        return tradingPeriod;
    }

    /**
     * Sets the value of the tradingPeriod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradingPeriod(String value) {
        this.tradingPeriod = value;
    }

    /**
     * Gets the value of the marketFactors property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketFactors property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketFactors().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketFactors }
     * 
     * 
     */
    public List<MarketFactors> getMarketFactors() {
        if (marketFactors == null) {
            marketFactors = new ArrayList<MarketFactors>();
        }
        return this.marketFactors;
    }

    /**
     * Gets the value of the marketRuns property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marketRuns property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarketRuns().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarketRun }
     * 
     * 
     */
    public List<MarketRun> getMarketRuns() {
        if (marketRuns == null) {
            marketRuns = new ArrayList<MarketRun>();
        }
        return this.marketRuns;
    }

}
