//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.greenenergycorp.openfmb.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Container_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Container");
    private final static QName _EndDeviceControl_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "EndDeviceControl");
    private final static QName _IdentifiedObject_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "IdentifiedObject");
    private final static QName _Status_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Status");
    private final static QName _Event_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Event");
    private final static QName _BasicIntervalSchedule_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "BasicIntervalSchedule");
    private final static QName _Curve_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/commonmodule", "Curve");
    private final static QName _Market_QNAME = new QName("http://openfmb.org/xsd/2015/12/openfmb/interchangemodule", "Market");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.greenenergycorp.openfmb.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BatterySystem }
     * 
     */
    public BatterySystem createBatterySystem() {
        return new BatterySystem();
    }

    /**
     * Create an instance of {@link IdentifiedObject }
     * 
     */
    public IdentifiedObject createIdentifiedObject() {
        return new IdentifiedObject();
    }

    /**
     * Create an instance of {@link BatteryControlProfile }
     * 
     */
    public BatteryControlProfile createBatteryControlProfile() {
        return new BatteryControlProfile();
    }

    /**
     * Create an instance of {@link Container }
     * 
     */
    public Container createContainer() {
        return new Container();
    }

    /**
     * Create an instance of {@link BatterySystemControl }
     * 
     */
    public BatterySystemControl createBatterySystemControl() {
        return new BatterySystemControl();
    }

    /**
     * Create an instance of {@link BatteryReadingProfile }
     * 
     */
    public BatteryReadingProfile createBatteryReadingProfile() {
        return new BatteryReadingProfile();
    }

    /**
     * Create an instance of {@link Reading }
     * 
     */
    public Reading createReading() {
        return new Reading();
    }

    /**
     * Create an instance of {@link BatteryEventProfile }
     * 
     */
    public BatteryEventProfile createBatteryEventProfile() {
        return new BatteryEventProfile();
    }

    /**
     * Create an instance of {@link BatteryStatus }
     * 
     */
    public BatteryStatus createBatteryStatus() {
        return new BatteryStatus();
    }

    /**
     * Create an instance of {@link EndDeviceControl }
     * 
     */
    public EndDeviceControl createEndDeviceControl() {
        return new EndDeviceControl();
    }

    /**
     * Create an instance of {@link DateTimeInterval }
     * 
     */
    public DateTimeInterval createDateTimeInterval() {
        return new DateTimeInterval();
    }

    /**
     * Create an instance of {@link EndDeviceControlType }
     * 
     */
    public EndDeviceControlType createEndDeviceControlType() {
        return new EndDeviceControlType();
    }

    /**
     * Create an instance of {@link SetPoint }
     * 
     */
    public SetPoint createSetPoint() {
        return new SetPoint();
    }

    /**
     * Create an instance of {@link Status }
     * 
     */
    public Status createStatus() {
        return new Status();
    }

    /**
     * Create an instance of {@link ActivePower }
     * 
     */
    public ActivePower createActivePower() {
        return new ActivePower();
    }

    /**
     * Create an instance of {@link Meter }
     * 
     */
    public Meter createMeter() {
        return new Meter();
    }

    /**
     * Create an instance of {@link PowerSystemResource }
     * 
     */
    public PowerSystemResource createPowerSystemResource() {
        return new PowerSystemResource();
    }

    /**
     * Create an instance of {@link Analog }
     * 
     */
    public Analog createAnalog() {
        return new Analog();
    }

    /**
     * Create an instance of {@link AnalogValue }
     * 
     */
    public AnalogValue createAnalogValue() {
        return new AnalogValue();
    }

    /**
     * Create an instance of {@link ReadingType }
     * 
     */
    public ReadingType createReadingType() {
        return new ReadingType();
    }

    /**
     * Create an instance of {@link Discrete }
     * 
     */
    public Discrete createDiscrete() {
        return new Discrete();
    }

    /**
     * Create an instance of {@link DiscreteValue }
     * 
     */
    public DiscreteValue createDiscreteValue() {
        return new DiscreteValue();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link BooleanMeasurement }
     * 
     */
    public BooleanMeasurement createBooleanMeasurement() {
        return new BooleanMeasurement();
    }

    /**
     * Create an instance of {@link BooleanMeasurementValue }
     * 
     */
    public BooleanMeasurementValue createBooleanMeasurementValue() {
        return new BooleanMeasurementValue();
    }

    /**
     * Create an instance of {@link BasicIntervalSchedule }
     * 
     */
    public BasicIntervalSchedule createBasicIntervalSchedule() {
        return new BasicIntervalSchedule();
    }

    /**
     * Create an instance of {@link ForecastSchedule }
     * 
     */
    public ForecastSchedule createForecastSchedule() {
        return new ForecastSchedule();
    }

    /**
     * Create an instance of {@link IrregularTimePoint }
     * 
     */
    public IrregularTimePoint createIrregularTimePoint() {
        return new IrregularTimePoint();
    }

    /**
     * Create an instance of {@link StringMeasurement }
     * 
     */
    public StringMeasurement createStringMeasurement() {
        return new StringMeasurement();
    }

    /**
     * Create an instance of {@link StringMeasurementValue }
     * 
     */
    public StringMeasurementValue createStringMeasurementValue() {
        return new StringMeasurementValue();
    }

    /**
     * Create an instance of {@link Curve }
     * 
     */
    public Curve createCurve() {
        return new Curve();
    }

    /**
     * Create an instance of {@link CurveData }
     * 
     */
    public CurveData createCurveData() {
        return new CurveData();
    }

    /**
     * Create an instance of {@link GenerationStatus }
     * 
     */
    public GenerationStatus createGenerationStatus() {
        return new GenerationStatus();
    }

    /**
     * Create an instance of {@link GeneratingUnit }
     * 
     */
    public GeneratingUnit createGeneratingUnit() {
        return new GeneratingUnit();
    }

    /**
     * Create an instance of {@link GenerationForecastProfile }
     * 
     */
    public GenerationForecastProfile createGenerationForecastProfile() {
        return new GenerationForecastProfile();
    }

    /**
     * Create an instance of {@link GenerationReadingProfile }
     * 
     */
    public GenerationReadingProfile createGenerationReadingProfile() {
        return new GenerationReadingProfile();
    }

    /**
     * Create an instance of {@link GenerationEventProfile }
     * 
     */
    public GenerationEventProfile createGenerationEventProfile() {
        return new GenerationEventProfile();
    }

    /**
     * Create an instance of {@link GenerationControlProfile }
     * 
     */
    public GenerationControlProfile createGenerationControlProfile() {
        return new GenerationControlProfile();
    }

    /**
     * Create an instance of {@link GenerationControl }
     * 
     */
    public GenerationControl createGenerationControl() {
        return new GenerationControl();
    }

    /**
     * Create an instance of {@link InterchangeSchedule }
     * 
     */
    public InterchangeSchedule createInterchangeSchedule() {
        return new InterchangeSchedule();
    }

    /**
     * Create an instance of {@link OptimizedMicroGridMarket }
     * 
     */
    public OptimizedMicroGridMarket createOptimizedMicroGridMarket() {
        return new OptimizedMicroGridMarket();
    }

    /**
     * Create an instance of {@link InterchangeScheduleProfile }
     * 
     */
    public InterchangeScheduleProfile createInterchangeScheduleProfile() {
        return new InterchangeScheduleProfile();
    }

    /**
     * Create an instance of {@link Market }
     * 
     */
    public Market createMarket() {
        return new Market();
    }

    /**
     * Create an instance of {@link MarketFactors }
     * 
     */
    public MarketFactors createMarketFactors() {
        return new MarketFactors();
    }

    /**
     * Create an instance of {@link MarketRun }
     * 
     */
    public MarketRun createMarketRun() {
        return new MarketRun();
    }

    /**
     * Create an instance of {@link EnergyConsumer }
     * 
     */
    public EnergyConsumer createEnergyConsumer() {
        return new EnergyConsumer();
    }

    /**
     * Create an instance of {@link LoadReadingProfile }
     * 
     */
    public LoadReadingProfile createLoadReadingProfile() {
        return new LoadReadingProfile();
    }

    /**
     * Create an instance of {@link LoadControlProfile }
     * 
     */
    public LoadControlProfile createLoadControlProfile() {
        return new LoadControlProfile();
    }

    /**
     * Create an instance of {@link LoadControl }
     * 
     */
    public LoadControl createLoadControl() {
        return new LoadControl();
    }

    /**
     * Create an instance of {@link LoadStatusProfile }
     * 
     */
    public LoadStatusProfile createLoadStatusProfile() {
        return new LoadStatusProfile();
    }

    /**
     * Create an instance of {@link LoadForecastProfile }
     * 
     */
    public LoadForecastProfile createLoadForecastProfile() {
        return new LoadForecastProfile();
    }

    /**
     * Create an instance of {@link RecloserControl }
     * 
     */
    public RecloserControl createRecloserControl() {
        return new RecloserControl();
    }

    /**
     * Create an instance of {@link RecloserReadingProfile }
     * 
     */
    public RecloserReadingProfile createRecloserReadingProfile() {
        return new RecloserReadingProfile();
    }

    /**
     * Create an instance of {@link Recloser }
     * 
     */
    public Recloser createRecloser() {
        return new Recloser();
    }

    /**
     * Create an instance of {@link RecloserEventProfile }
     * 
     */
    public RecloserEventProfile createRecloserEventProfile() {
        return new RecloserEventProfile();
    }

    /**
     * Create an instance of {@link RecloserStatus }
     * 
     */
    public RecloserStatus createRecloserStatus() {
        return new RecloserStatus();
    }

    /**
     * Create an instance of {@link RecloserControlProfile }
     * 
     */
    public RecloserControlProfile createRecloserControlProfile() {
        return new RecloserControlProfile();
    }

    /**
     * Create an instance of {@link RegulatorStatusProfile }
     * 
     */
    public RegulatorStatusProfile createRegulatorStatusProfile() {
        return new RegulatorStatusProfile();
    }

    /**
     * Create an instance of {@link RegulatorSystem }
     * 
     */
    public RegulatorSystem createRegulatorSystem() {
        return new RegulatorSystem();
    }

    /**
     * Create an instance of {@link RegulatorReadingProfile }
     * 
     */
    public RegulatorReadingProfile createRegulatorReadingProfile() {
        return new RegulatorReadingProfile();
    }

    /**
     * Create an instance of {@link ResourceReadingProfile }
     * 
     */
    public ResourceReadingProfile createResourceReadingProfile() {
        return new ResourceReadingProfile();
    }

    /**
     * Create an instance of {@link ResourceStatusProfile }
     * 
     */
    public ResourceStatusProfile createResourceStatusProfile() {
        return new ResourceStatusProfile();
    }

    /**
     * Create an instance of {@link SecurityEvent }
     * 
     */
    public SecurityEvent createSecurityEvent() {
        return new SecurityEvent();
    }

    /**
     * Create an instance of {@link SecurityEventProfile }
     * 
     */
    public SecurityEventProfile createSecurityEventProfile() {
        return new SecurityEventProfile();
    }

    /**
     * Create an instance of {@link ShuntStatusProfile }
     * 
     */
    public ShuntStatusProfile createShuntStatusProfile() {
        return new ShuntStatusProfile();
    }

    /**
     * Create an instance of {@link ShuntSystem }
     * 
     */
    public ShuntSystem createShuntSystem() {
        return new ShuntSystem();
    }

    /**
     * Create an instance of {@link ShuntControlProfile }
     * 
     */
    public ShuntControlProfile createShuntControlProfile() {
        return new ShuntControlProfile();
    }

    /**
     * Create an instance of {@link ShuntControl }
     * 
     */
    public ShuntControl createShuntControl() {
        return new ShuntControl();
    }

    /**
     * Create an instance of {@link ShuntReadingProfile }
     * 
     */
    public ShuntReadingProfile createShuntReadingProfile() {
        return new ShuntReadingProfile();
    }

    /**
     * Create an instance of {@link SolarInverter }
     * 
     */
    public SolarInverter createSolarInverter() {
        return new SolarInverter();
    }

    /**
     * Create an instance of {@link SolarControlProfile }
     * 
     */
    public SolarControlProfile createSolarControlProfile() {
        return new SolarControlProfile();
    }

    /**
     * Create an instance of {@link SolarControl }
     * 
     */
    public SolarControl createSolarControl() {
        return new SolarControl();
    }

    /**
     * Create an instance of {@link SolarReadingProfile }
     * 
     */
    public SolarReadingProfile createSolarReadingProfile() {
        return new SolarReadingProfile();
    }

    /**
     * Create an instance of {@link SolarEventProfile }
     * 
     */
    public SolarEventProfile createSolarEventProfile() {
        return new SolarEventProfile();
    }

    /**
     * Create an instance of {@link SolarInverterStatus }
     * 
     */
    public SolarInverterStatus createSolarInverterStatus() {
        return new SolarInverterStatus();
    }

    /**
     * Create an instance of {@link SolarCapabilityProfile }
     * 
     */
    public SolarCapabilityProfile createSolarCapabilityProfile() {
        return new SolarCapabilityProfile();
    }

    /**
     * Create an instance of {@link SolarCapability }
     * 
     */
    public SolarCapability createSolarCapability() {
        return new SolarCapability();
    }

    /**
     * Create an instance of {@link SolarForecastProfile }
     * 
     */
    public SolarForecastProfile createSolarForecastProfile() {
        return new SolarForecastProfile();
    }

    /**
     * Create an instance of {@link TelecomData }
     * 
     */
    public TelecomData createTelecomData() {
        return new TelecomData();
    }

    /**
     * Create an instance of {@link HumidityData }
     * 
     */
    public HumidityData createHumidityData() {
        return new HumidityData();
    }

    /**
     * Create an instance of {@link SunRadiationData }
     * 
     */
    public SunRadiationData createSunRadiationData() {
        return new SunRadiationData();
    }

    /**
     * Create an instance of {@link TemperatureData }
     * 
     */
    public TemperatureData createTemperatureData() {
        return new TemperatureData();
    }

    /**
     * Create an instance of {@link WindData }
     * 
     */
    public WindData createWindData() {
        return new WindData();
    }

    /**
     * Create an instance of {@link WeatherDataProfile }
     * 
     */
    public WeatherDataProfile createWeatherDataProfile() {
        return new WeatherDataProfile();
    }

    /**
     * Create an instance of {@link WeatherData }
     * 
     */
    public WeatherData createWeatherData() {
        return new WeatherData();
    }

    /**
     * Create an instance of {@link Humidity }
     * 
     */
    public Humidity createHumidity() {
        return new Humidity();
    }

    /**
     * Create an instance of {@link SunRadiation }
     * 
     */
    public SunRadiation createSunRadiation() {
        return new SunRadiation();
    }

    /**
     * Create an instance of {@link Temperature }
     * 
     */
    public Temperature createTemperature() {
        return new Temperature();
    }

    /**
     * Create an instance of {@link Wind }
     * 
     */
    public Wind createWind() {
        return new Wind();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Container }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Container")
    public JAXBElement<Container> createContainer(Container value) {
        return new JAXBElement<Container>(_Container_QNAME, Container.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EndDeviceControl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "EndDeviceControl")
    public JAXBElement<EndDeviceControl> createEndDeviceControl(EndDeviceControl value) {
        return new JAXBElement<EndDeviceControl>(_EndDeviceControl_QNAME, EndDeviceControl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IdentifiedObject }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "IdentifiedObject")
    public JAXBElement<IdentifiedObject> createIdentifiedObject(IdentifiedObject value) {
        return new JAXBElement<IdentifiedObject>(_IdentifiedObject_QNAME, IdentifiedObject.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Status }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Status")
    public JAXBElement<Status> createStatus(Status value) {
        return new JAXBElement<Status>(_Status_QNAME, Status.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Event }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Event")
    public JAXBElement<Event> createEvent(Event value) {
        return new JAXBElement<Event>(_Event_QNAME, Event.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BasicIntervalSchedule }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "BasicIntervalSchedule")
    public JAXBElement<BasicIntervalSchedule> createBasicIntervalSchedule(BasicIntervalSchedule value) {
        return new JAXBElement<BasicIntervalSchedule>(_BasicIntervalSchedule_QNAME, BasicIntervalSchedule.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Curve }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/commonmodule", name = "Curve")
    public JAXBElement<Curve> createCurve(Curve value) {
        return new JAXBElement<Curve>(_Curve_QNAME, Curve.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Market }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openfmb.org/xsd/2015/12/openfmb/interchangemodule", name = "Market")
    public JAXBElement<Market> createMarket(Market value) {
        return new JAXBElement<Market>(_Market_QNAME, Market.class, null, value);
    }

}
