//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PhaseCodeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PhaseCodeKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="AB"/&gt;
 *     &lt;enumeration value="ABC"/&gt;
 *     &lt;enumeration value="ABCN"/&gt;
 *     &lt;enumeration value="ABN"/&gt;
 *     &lt;enumeration value="AC"/&gt;
 *     &lt;enumeration value="ACN"/&gt;
 *     &lt;enumeration value="AN"/&gt;
 *     &lt;enumeration value="B"/&gt;
 *     &lt;enumeration value="BC"/&gt;
 *     &lt;enumeration value="BCN"/&gt;
 *     &lt;enumeration value="BN"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="CN"/&gt;
 *     &lt;enumeration value="N"/&gt;
 *     &lt;enumeration value="noPhase"/&gt;
 *     &lt;enumeration value="s1"/&gt;
 *     &lt;enumeration value="s12"/&gt;
 *     &lt;enumeration value="s12N"/&gt;
 *     &lt;enumeration value="s1N"/&gt;
 *     &lt;enumeration value="s2"/&gt;
 *     &lt;enumeration value="s2N"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PhaseCodeKind")
@XmlEnum
public enum PhaseCodeKind {


    /**
     * Phase A.
     * 
     */
    A("A"),

    /**
     * Phases A and B.
     * 
     */
    AB("AB"),

    /**
     * Phases A, B, and C.
     * 
     */
    ABC("ABC"),

    /**
     * Phases A, B, C, and N.
     * 
     */
    ABCN("ABCN"),

    /**
     * Phases A, B, and neutral.
     * 
     */
    ABN("ABN"),

    /**
     * Phases A and C.
     * 
     */
    AC("AC"),

    /**
     * Phases A, C and neutral.
     * 
     */
    ACN("ACN"),

    /**
     * Phases A and neutral.
     * 
     */
    AN("AN"),

    /**
     * Phase B.
     * 
     */
    B("B"),

    /**
     * Phases B and C.
     * 
     */
    BC("BC"),

    /**
     * Phases B, C, and neutral.
     * 
     */
    BCN("BCN"),

    /**
     * Phases B and neutral.
     * 
     */
    BN("BN"),

    /**
     * Phase C.
     * 
     */
    C("C"),

    /**
     * Phases C and neutral.
     * 
     */
    CN("CN"),

    /**
     * Neutral phase.
     * 
     */
    N("N"),

    /**
     * Not applicable
     * 
     */
    @XmlEnumValue("noPhase")
    NO_PHASE("noPhase"),

    /**
     * Secondary phase 1.
     * 
     */
    @XmlEnumValue("s1")
    S_1("s1"),

    /**
     * Secondary phase 1 and 2.
     * 
     */
    @XmlEnumValue("s12")
    S_12("s12"),

    /**
     * Secondary phases 1, 2, and neutral.
     * 
     */
    @XmlEnumValue("s12N")
    S_12_N("s12N"),

    /**
     * Secondary phase 1 and neutral.
     * 
     */
    @XmlEnumValue("s1N")
    S_1_N("s1N"),

    /**
     * Secondary phase 2.
     * 
     */
    @XmlEnumValue("s2")
    S_2("s2"),

    /**
     * Secondary phase 2 and neutral.
     * 
     */
    @XmlEnumValue("s2N")
    S_2_N("s2N");
    private final String value;

    PhaseCodeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PhaseCodeKind fromValue(String v) {
        for (PhaseCodeKind c: PhaseCodeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
