//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecloserStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecloserStatus"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Status"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="isBlocked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="switchStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}SwitchStatusKind" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecloserStatus", namespace = "http://openfmb.org/xsd/2015/12/openfmb/reclosermodule", propOrder = {
    "isBlocked",
    "switchStatus"
})
@XmlRootElement(name = "RecloserStatus", namespace = "http://openfmb.org/xsd/2015/12/openfmb/reclosermodule")
public class RecloserStatus
    extends Status
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    protected Boolean isBlocked;
    @XmlSchemaType(name = "string")
    protected SwitchStatusKind switchStatus;

    /**
     * Gets the value of the isBlocked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBlocked() {
        return isBlocked;
    }

    /**
     * Sets the value of the isBlocked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBlocked(Boolean value) {
        this.isBlocked = value;
    }

    /**
     * Gets the value of the switchStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchStatusKind }
     *     
     */
    public SwitchStatusKind getSwitchStatus() {
        return switchStatus;
    }

    /**
     * Sets the value of the switchStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchStatusKind }
     *     
     */
    public void setSwitchStatus(SwitchStatusKind value) {
        this.switchStatus = value;
    }

}
