//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecloserEventProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecloserEventProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Recloser" type="{http://openfmb.org/xsd/2015/12/openfmb/reclosermodule}Recloser"/&gt;
 *         &lt;element name="RecloserStatus" type="{http://openfmb.org/xsd/2015/12/openfmb/reclosermodule}RecloserStatus"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecloserEventProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/reclosermodule", propOrder = {
    "recloser",
    "recloserStatus"
})
@XmlRootElement(name = "RecloserEventProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/reclosermodule")
public class RecloserEventProfile
    extends Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Recloser", required = true)
    protected Recloser recloser;
    @XmlElement(name = "RecloserStatus", required = true)
    protected RecloserStatus recloserStatus;

    /**
     * Gets the value of the recloser property.
     * 
     * @return
     *     possible object is
     *     {@link Recloser }
     *     
     */
    public Recloser getRecloser() {
        return recloser;
    }

    /**
     * Sets the value of the recloser property.
     * 
     * @param value
     *     allowed object is
     *     {@link Recloser }
     *     
     */
    public void setRecloser(Recloser value) {
        this.recloser = value;
    }

    /**
     * Gets the value of the recloserStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RecloserStatus }
     *     
     */
    public RecloserStatus getRecloserStatus() {
        return recloserStatus;
    }

    /**
     * Sets the value of the recloserStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecloserStatus }
     *     
     */
    public void setRecloserStatus(RecloserStatus value) {
        this.recloserStatus = value;
    }

}
