//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Load forecast.
 * 
 * <p>Java class for SecurityEventProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityEventProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SecurityEvent" type="{http://openfmb.org/xsd/2015/12/openfmb/securitymodule}SecurityEvent"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityEventProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/securitymodule", propOrder = {
    "securityEvent"
})
@XmlRootElement(name = "SecurityEventProfile", namespace = "http://openfmb.org/xsd/2015/12/openfmb/securitymodule")
public class SecurityEventProfile
    extends Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "SecurityEvent", required = true)
    protected SecurityEvent securityEvent;

    /**
     * Gets the value of the securityEvent property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityEvent }
     *     
     */
    public SecurityEvent getSecurityEvent() {
        return securityEvent;
    }

    /**
     * Sets the value of the securityEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityEvent }
     *     
     */
    public void setSecurityEvent(SecurityEvent value) {
        this.securityEvent = value;
    }

}
