//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Resource status module
 * 
 * <p>Java class for ShuntStatusProfile complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShuntStatusProfile"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Container"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Analogs" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Analog" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="BooleanMeasurements" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}BooleanMeasurement" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="Discretes" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}Discrete" maxOccurs="100" minOccurs="0"/&gt;
 *         &lt;element name="ShuntSystem" type="{http://openfmb.org/xsd/2016/04/openfmb/shuntmodule}ShuntSystem"/&gt;
 *         &lt;element name="StringMeasurements" type="{http://openfmb.org/xsd/2015/12/openfmb/commonmodule}StringMeasurement" maxOccurs="100" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShuntStatusProfile", namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule", propOrder = {
    "analogs",
    "booleanMeasurements",
    "discretes",
    "shuntSystem",
    "stringMeasurements"
})
@XmlRootElement(name = "ShuntStatusProfile", namespace = "http://openfmb.org/xsd/2016/04/openfmb/shuntmodule")
public class ShuntStatusProfile
    extends Container
    implements Serializable
{

    private final static long serialVersionUID = 1L;
    @XmlElement(name = "Analogs")
    protected List<Analog> analogs;
    @XmlElement(name = "BooleanMeasurements")
    protected List<BooleanMeasurement> booleanMeasurements;
    @XmlElement(name = "Discretes")
    protected List<Discrete> discretes;
    @XmlElement(name = "ShuntSystem", required = true)
    protected ShuntSystem shuntSystem;
    @XmlElement(name = "StringMeasurements")
    protected List<StringMeasurement> stringMeasurements;

    /**
     * Gets the value of the analogs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the analogs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAnalogs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Analog }
     * 
     * 
     */
    public List<Analog> getAnalogs() {
        if (analogs == null) {
            analogs = new ArrayList<Analog>();
        }
        return this.analogs;
    }

    /**
     * Gets the value of the booleanMeasurements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the booleanMeasurements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBooleanMeasurements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BooleanMeasurement }
     * 
     * 
     */
    public List<BooleanMeasurement> getBooleanMeasurements() {
        if (booleanMeasurements == null) {
            booleanMeasurements = new ArrayList<BooleanMeasurement>();
        }
        return this.booleanMeasurements;
    }

    /**
     * Gets the value of the discretes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the discretes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiscretes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Discrete }
     * 
     * 
     */
    public List<Discrete> getDiscretes() {
        if (discretes == null) {
            discretes = new ArrayList<Discrete>();
        }
        return this.discretes;
    }

    /**
     * Gets the value of the shuntSystem property.
     * 
     * @return
     *     possible object is
     *     {@link ShuntSystem }
     *     
     */
    public ShuntSystem getShuntSystem() {
        return shuntSystem;
    }

    /**
     * Sets the value of the shuntSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShuntSystem }
     *     
     */
    public void setShuntSystem(ShuntSystem value) {
        this.shuntSystem = value;
    }

    /**
     * Gets the value of the stringMeasurements property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stringMeasurements property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStringMeasurements().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StringMeasurement }
     * 
     * 
     */
    public List<StringMeasurement> getStringMeasurements() {
        if (stringMeasurements == null) {
            stringMeasurements = new ArrayList<StringMeasurement>();
        }
        return this.stringMeasurements;
    }

}
