//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.27 at 02:07:42 PM EDT 
//


package com.greenenergycorp.openfmb.xml;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnitMultiplierKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnitMultiplierKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="centi"/&gt;
 *     &lt;enumeration value="deci"/&gt;
 *     &lt;enumeration value="Giga"/&gt;
 *     &lt;enumeration value="kilo"/&gt;
 *     &lt;enumeration value="milli"/&gt;
 *     &lt;enumeration value="Mega"/&gt;
 *     &lt;enumeration value="micro"/&gt;
 *     &lt;enumeration value="nano"/&gt;
 *     &lt;enumeration value="noMultiplier"/&gt;
 *     &lt;enumeration value="pico"/&gt;
 *     &lt;enumeration value="Tera"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "UnitMultiplierKind")
@XmlEnum
public enum UnitMultiplierKind {


    /**
     * Centi 10**-2.
     * 
     */
    @XmlEnumValue("centi")
    CENTI("centi"),

    /**
     * Deci 10**-1.
     * 
     */
    @XmlEnumValue("deci")
    DECI("deci"),

    /**
     * Giga 10**9.
     * 
     */
    @XmlEnumValue("Giga")
    GIGA("Giga"),

    /**
     * Kilo 10**3.
     * 
     */
    @XmlEnumValue("kilo")
    KILO("kilo"),

    /**
     * Milli 10**-3.
     * 
     */
    @XmlEnumValue("milli")
    MILLI("milli"),

    /**
     * Mega 10**6.
     * 
     */
    @XmlEnumValue("Mega")
    MEGA("Mega"),

    /**
     * Micro 10**-6.
     * 
     */
    @XmlEnumValue("micro")
    MICRO("micro"),

    /**
     * Nano 10**-9.
     * 
     */
    @XmlEnumValue("nano")
    NANO("nano"),

    /**
     * No multiplier or equivalently multiply by 1.
     * 
     */
    @XmlEnumValue("noMultiplier")
    NO_MULTIPLIER("noMultiplier"),

    /**
     * Pico 10**-12.
     * 
     */
    @XmlEnumValue("pico")
    PICO("pico"),

    /**
     * Tera 10**12.
     * 
     */
    @XmlEnumValue("Tera")
    TERA("Tera");
    private final String value;

    UnitMultiplierKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UnitMultiplierKind fromValue(String v) {
        for (UnitMultiplierKind c: UnitMultiplierKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
